[tox]
envlist = py39, py310, py311, py312, flake8, mypy

[testenv]
deps = pytest
       pytest-cov
commands = pytest tests/ -v --cov=visuai --cov-report=term-missing

[testenv:flake8]
deps = flake8
commands = flake8 src/visuai

[testenv:mypy]
deps = mypy
commands = mypy src/visuai --ignore-missing-imports
